function [turtle_nm, turtle_name, name_table_agm, name_table_axy, name_table_calib, turtle_raw_name, turtle_ypr_name, turtle_dive_name, turtle_dive_plt_name, turtle_dive_fft_name, turtle_DBA_name, turtle_DBA_name_paper, turtle_dive_name_din, turtle_dive_plt_name_din, turtle_dive_fft_name_din, turtle_DBA_name_paper_din, turtle_freq_name, carapace_model] = turtle_info(turtle_nm, release)
% turtle_info
% Function that allows to select the turtle (from the Dalmag 2023 dataset) to
% be analysed through a "command window" selection of the name. After that,
% the name of the .csv files containing the dataset corresponding to the
% selected turtle are saved and the name of the .mat files that will be
% generated by the code will be created.

%% name of the structs to be saved as Matlab variable files

if release == 1
    %% 2023
    if turtle_nm == 0
        turtle_nm = -2;

        turtle_max = 9;
        fprintf('Turtle name: \n')
        fprintf('1. Melis \n')
        fprintf('2. Banu \n')
        fprintf('3. Fati \n')
        fprintf('4. Emine \n')
        fprintf('5. Sevval \n')
        fprintf('6. Didar \n')
        fprintf('7. Deniz \n')
        fprintf('8. Elif \n')
        fprintf('9. Funda \n')
        fprintf('0. General \n')

        while turtle_nm < 0 || turtle_nm > turtle_max
            turtle_nm = input('');
        end
    end

    if turtle_nm == 1
        turtle_name		= 'Melis';
        name_table_agm	= 'Melis_agm.csv';
        name_table_axy	= 'Melis_axy.csv';
        name_table_calib = 'Melis_agm.csv';
        carapace_model = 'agm';

    elseif turtle_nm == 2
        turtle_name		= 'Banu';
        name_table_agm	= 'Banu_agm.csv';
        name_table_axy	= 'Banu_axy.csv';
        name_table_calib = 'Banu_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 3
        turtle_name		= 'Fati';
        name_table_agm	= 'Fati_agm.csv';
        name_table_axy	= 'Fati_axy.csv';
        name_table_calib = 'Fati_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 4
        turtle_name		= 'Emine';
        name_table_agm	= 'Emine_agm.csv';
        name_table_axy	= 'Emine_axy.csv';
        name_table_calib = 'Emine_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 5
        turtle_name		= 'Sevval';
        name_table_agm	= 'Sevval_agm.csv';
        name_table_axy	= 'Sevval_axy.csv';
        name_table_calib = 'Sevval_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 6
        turtle_name		= 'Didar';
        name_table_agm	= 'Didar_agm.csv';
        name_table_axy	= 'Didar_axy.csv';
        name_table_calib = 'Didar_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 7
        turtle_name		= 'Deniz';
        name_table_agm	= 'Deniz_agm.csv';
        name_table_axy	= 'Deniz_axy.csv';
        name_table_calib = 'Deniz_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 8
        turtle_name		= 'Elif';
        name_table_agm	= 'Elif_agm.csv';
        name_table_axy	= 'Elif_axy.csv';
        name_table_calib = 'Elif_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 9
        turtle_name		= 'Funda';
        name_table_agm	= 'Funda_agm.csv';
        name_table_axy	= 'Funda_axy.csv';
        name_table_calib = 'Funda_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 0
        turtle_name		= 'Calib_test';
        name_table_agm	= 'Calib_test.csv';
        name_table_axy	= 'Calib_test.csv';
        name_table_calib = 'Calib_test.csv';
        carapace_model = 'agm';
        
        calib_proc_real_time = 1;
        fprintf('calib_proc_real_time created');
    end

    %% 2024
elseif release == 2
    if turtle_nm == 0
        turtle_nm = -2;

    	turtle_max = 10;
    	fprintf('Turtle name: \n')
    	fprintf('1. Enes \n')
    	fprintf('2. Atakan \n')
    	fprintf('3. Fatma \n')
    	fprintf('4. Ilkim \n')
    	fprintf('5. Nurdan \n')
    	fprintf('6. Paula (2nd release) - no AGM \n')
    	fprintf('7. Arya (2nd release) - no AGM \n')
    	fprintf('8. Bihter (2nd release)  - no AGM \n')
    	fprintf('9. Erica (2nd release) \n')
    	fprintf('10. Benedetta (2nd release)  - no AGM \n')
        fprintf('0. General \n')

    	while turtle_nm < 0 || turtle_nm > turtle_max
    		turtle_nm = input('');
    	end
    end

    if turtle_nm == 1
    	turtle_name		= 'Enes';
    	name_table_agm	= 'Enes_agm.csv';
    	name_table_axy	= 'Enes_axy.csv';
    	name_table_calib = 'Enes_agm_calib.csv';
        carapace_model = 'agm';
        

    elseif turtle_nm == 2
    	turtle_name		= 'Atakan';
    	name_table_agm	= 'Atakan_agm.csv';
    	name_table_axy	= 'Atakan_axy.csv';
     	name_table_calib = 'Atakan_agm_calib.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 3
    	turtle_name		= 'Fatma';
    	name_table_agm	= 'Fatma_agm.csv';
    	name_table_axy	= 'Fatma_axy.csv';
    	name_table_calib = 'Fatma_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 4
    	turtle_name		= 'Ilkim';
    	name_table_agm	= 'Ilkim_agm.csv';
    	name_table_axy	= 'Ilkim_axy.csv';
    	name_table_calib = 'Ilkim_agm_calib.csv';
        carapace_model = 'axy';
        
    elseif turtle_nm == 5
    	turtle_name		= 'Nurdan';
    	name_table_agm	= 'Nurdan_agm.csv';
    	name_table_axy	= 'Nurdan_axy.csv';
    	name_table_calib = 'Nurdan_agm_calib.csv';
        carapace_model = 'axy';
        
    elseif turtle_nm == 6
    	turtle_name		= 'Paula';
    	name_table_agm	= 'Paula_agm.csv';
    	name_table_axy	= 'Paula_axy.csv';
    	name_table_calib = 'Paula_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 7
    	turtle_name		= 'Arya';
    	name_table_agm	= 'Arya_agm.csv';
    	name_table_axy	= 'Arya_axy.csv';
    	name_table_calib = 'Arya_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 8
    	turtle_name		= 'Bihter';
    	name_table_agm	= 'Bihter_agm.csv';
    	name_table_axy	= 'Bihter_axy.csv';
    	name_table_calib = 'Bihter_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 9
    	turtle_name		= 'Erica';
    	name_table_agm	= 'Erica_agm.csv';
    	name_table_axy	= 'Erica_axy.csv';
    	name_table_calib = 'Erica_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 10
    	turtle_name		= 'Benedetta';
    	name_table_agm	= 'Benedetta_agm.csv';
    	name_table_axy	= 'Benedetta_axy.csv';
    	name_table_calib = 'Benedetta_agm.csv';
        carapace_model = 'agm';
        
    elseif turtle_nm == 0
        turtle_name		= 'Calib_test';
        name_table_agm	= 'Calib_test.csv';
        name_table_axy	= 'Calib_test.csv';
        name_table_calib = 'Calib_test.csv';
        carapace_model = 'agm';
        
        calib_proc_real_time = 1;
        fprintf('calib_proc_real_time created');

    end

elseif release == 3
    auto_calib_datetime	 = 0;
    auto_freq_selection = 0;
       
    prompt= 'Turtle name ';
    turtle_name = input(prompt, 's');
    prompt= 'Carapace sensor (agm) file name (include .csv) ';
    name_table_agm = input(prompt, 's');
	prompt= 'Head sensor (axy) file name (include .csv) ';
	name_table_axy	= input(prompt, 's');
	prompt= 'Carapace sensor (agm) calibration file name (include .csv) ';
	name_table_calib = input(prompt, 's');
    prompt= 'Carapace sensor model (agm or axy) ';
    carapace_model = input(prompt, 's');
    
end

formatSpec = 'turtle_raw_%s.mat';
turtle_raw_name = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_ypr_%s.mat';
turtle_ypr_name = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_dive_%s.mat';
turtle_dive_name = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_dive_plt_%s.mat';
turtle_dive_plt_name = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_dive_fft_%s.mat';
turtle_dive_fft_name = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_DBA_%s.mat';
turtle_DBA_name = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_DBA_paper_%s.mat';
turtle_DBA_name_paper = string(compose(formatSpec, turtle_name));

formatSpec = 'turtle_dive_din_%s.mat';
turtle_dive_name_din = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_dive_din_plt_%s.mat';
turtle_dive_plt_name_din = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_dive_fft_din_%s.mat';
turtle_dive_fft_name_din = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_DBA_paper_din_%s.mat';
turtle_DBA_name_paper_din = string(compose(formatSpec, turtle_name));
formatSpec = 'turtle_freq_%s.mat';
turtle_freq_name = string(compose(formatSpec, turtle_name));

end