function [turtle_nm, turtle_name, name_table_agm, name_table_axy, name_table_calib, turtle_raw_name, turtle_ypr_name, turtle_dive_name, turtle_dive_plt_name, turtle_dive_fft_name, turtle_DBA_name, turtle_DBA_name_paper, turtle_dive_name_din, turtle_dive_plt_name_din, turtle_dive_fft_name_din, turtle_DBA_name_paper_din, turtle_freq_name] = turtle_info(turtle_nm)
% turtle_info
% Function that allows to select the turtle (from the Dalmag 2023 dataset) to
% be analysed through a "command window" selection of the name. After that,
% the name of the .csv files containing the dataset corresponding to the
% selected turtle are saved and the name of the .mat files that will be
% generated by the code will be created.

%% name of the structs to be saved as Matlab variable files
if turtle_nm == 0
	turtle_max = 9;
	fprintf('Turtle name: \n')
	fprintf('1. Melis \n')
	fprintf('2. Banu \n')
	fprintf('3. Fati \n')
	fprintf('4. Emine \n')
	fprintf('5. Sevval \n')
	fprintf('6. Didar \n')
	fprintf('7. Deniz \n')
	fprintf('8. Elif \n')
	fprintf('9. Funda \n')
    fprintf('0. General \n')

	while turtle_nm <= 0 || turtle_nm > turtle_max
		turtle_nm = input('');
	end
end

if turtle_nm == 1
	turtle_name		= 'Melis';
	name_table_agm	= 'Melis_agm.csv';
	name_table_axy	= 'Melis_axy.csv';
	name_table_calib = 'Melis_agm.csv';
	turtle_raw_name			= 'turtle_raw_Melis.mat';
	turtle_ypr_name			= 'turtle_ypr_Melis.mat';
	turtle_dive_name		= 'turtle_dive_Melis.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Melis.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Melis.mat';
	turtle_DBA_name			= 'turtle_DBA_Melis.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Melis.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Melis.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Melis.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Melis.mat';
	turtle_DBA_name_paper_din		= 'turtle_DBA_paper_din_Melis.mat';

	turtle_freq_name		= 'turtle_freq_Melis.mat';
	
elseif turtle_nm == 2
	turtle_name		= 'Banu';
	name_table_agm	= 'Banu_agm.csv'; 
	name_table_axy	= 'Banu_axy.csv';
	name_table_calib = 'Banu_agm.csv';
	turtle_raw_name			= 'turtle_raw_Banu.mat';
	turtle_ypr_name			= 'turtle_ypr_Banu.mat';
	turtle_dive_name		= 'turtle_dive_Banu.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Banu.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Banu.mat';
	turtle_DBA_name			= 'turtle_DBA_Banu.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Banu.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Banu.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Banu.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Banu.mat';
	turtle_DBA_name_paper_din		= 'turtle_DBA_paper_din_Banu.mat';

	turtle_freq_name		= 'turtle_freq_Banu.mat';
	
elseif turtle_nm == 3
	turtle_name		= 'Fati';
	name_table_agm	= 'Fati_agm.csv'; 
	name_table_axy	= 'Fati_axy.csv';
	name_table_calib = 'Fati_agm.csv';
	turtle_raw_name			= 'turtle_raw_Fati.mat';
	turtle_ypr_name			= 'turtle_ypr_Fati.mat';
	turtle_dive_name		= 'turtle_dive_Fati.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Fati.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Fati.mat';
	turtle_DBA_name			= 'turtle_DBA_Fati.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Fati.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Fati.mat';
	turtle_dive_plt_name_din		= 'turtle_dive_din_plt_Fati.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Fati.mat';
	turtle_DBA_name_paper_din		= 'turtle_DBA_paper_din_Fati.mat';
	
	turtle_freq_name		= 'turtle_freq_Fati.mat';
	
elseif turtle_nm == 4
	turtle_name		= 'Emine';
	name_table_agm	= 'Emine_agm.csv'; 
	name_table_axy	= 'Emine_axy.csv';
	name_table_calib = 'Emine_agm.csv';
	turtle_raw_name			= 'turtle_raw_Emine.mat';
	turtle_ypr_name			= 'turtle_ypr_Emine.mat';
	turtle_dive_name		= 'turtle_dive_Emine.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Emine.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Emine.mat';
	turtle_DBA_name			= 'turtle_DBA_Emine.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Emine.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Emine.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Emine.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Emine.mat';
	turtle_DBA_name_paper_din		= 'turtle_DBA_paper_din_Emine.mat';
	
	turtle_freq_name		= 'turtle_freq_Emine.mat';
	
elseif turtle_nm == 5
	turtle_name		= 'Sevval';
	name_table_agm	= 'Sevval_agm.csv'; 
	name_table_axy	= 'Sevval_axy.csv'; 
	name_table_calib = 'Sevval_agm.csv';
	turtle_raw_name			= 'turtle_raw_Sevval.mat';
	turtle_ypr_name			= 'turtle_ypr_Sevval.mat';
	turtle_dive_name		= 'turtle_dive_Sevval.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Sevval.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Sevval.mat';
	turtle_DBA_name			= 'turtle_DBA_Sevval.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Sevval.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Sevval.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Sevval.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Sevval.mat';
	turtle_DBA_name_paper_din	= 'turtle_DBA_paper_din_Sevval.mat';
	
	turtle_freq_name		= 'turtle_freq_Sevval.mat';
	
elseif turtle_nm == 6
	turtle_name		= 'Didar';
	name_table_agm	= 'Didar_agm.csv'; 
	name_table_axy	= 'Didar_axy.csv'; 
	name_table_calib = 'Didar_agm.csv';
	turtle_raw_name			= 'turtle_raw_Didar.mat';
	turtle_ypr_name			= 'turtle_ypr_Didar.mat';
	turtle_dive_name		= 'turtle_dive_Didar.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Didar.mat';
	turtle_DBA_name			= 'turtle_DBA_Didar.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Didar.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Didar.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Didar.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Didar.mat';
	turtle_DBA_name_paper_din	= 'turtle_DBA_paper_din_Didar.mat';
	
	turtle_freq_name		= 'turtle_freq_Didar.mat';
	
elseif turtle_nm == 7
	turtle_name		= 'Deniz';
	name_table_agm	= 'Deniz_agm.csv'; 
	name_table_axy	= 'Deniz_axy.csv'; 
	name_table_calib = 'Deniz_agm.csv';
	turtle_raw_name			= 'turtle_raw_Deniz.mat';
	turtle_ypr_name			= 'turtle_ypr_Deniz.mat';
	turtle_dive_name		= 'turtle_dive_Deniz.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Deniz.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Deniz.mat';
	turtle_DBA_name			= 'turtle_DBA_Deniz.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Deniz.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Didar.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Didar.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Didar.mat';
	turtle_DBA_name_paper_din	= 'turtle_DBA_paper_din_Didar.mat';
	
	turtle_freq_name		= 'turtle_freq_Deniz.mat';
	
elseif turtle_nm == 8
	turtle_name		= 'Elif';
	name_table_agm	= 'Elif_agm.csv'; 
	name_table_axy	= 'Elif_axy.csv'; 
	name_table_calib = 'Elif_agm.csv';
	turtle_raw_name			= 'turtle_raw_Elif.mat';
	turtle_ypr_name			= 'turtle_ypr_Elif.mat';
	turtle_dive_name		= 'turtle_dive_Elif.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Elif.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Elif.mat';
	turtle_DBA_name			= 'turtle_DBA_Elif.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Elif.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Elif.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Elif.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Elif.mat';
	turtle_DBA_name_paper_din		= 'turtle_DBA_paper_din_Elif.mat';
	
	turtle_freq_name		= 'turtle_freq_Elif.mat';
	
elseif turtle_nm == 9
	turtle_name		= 'Funda';
	name_table_agm	= 'Funda_agm.csv'; 
	name_table_axy	= 'Funda_axy.csv'; 
	name_table_calib = 'Funda_agm.csv';
	turtle_raw_name			= 'turtle_raw_Funda.mat';
	turtle_ypr_name			= 'turtle_ypr_Funda.mat';
	turtle_dive_name		= 'turtle_dive_Funda.mat';
	turtle_dive_plt_name	= 'turtle_dive_plt_Funda.mat';
	turtle_dive_fft_name	= 'turtle_dive_fft_Funda.mat';
	turtle_DBA_name			= 'turtle_DBA_Funda.mat';
	turtle_DBA_name_paper	= 'turtle_DBA_paper_Funda.mat';
	
	turtle_dive_name_din		= 'turtle_dive_din_Funda.mat';
	turtle_dive_plt_name_din	= 'turtle_dive_din_plt_Funda.mat';
	turtle_dive_fft_name_din	= 'turtle_dive_fft_din_Funda.mat';
	turtle_DBA_name_paper_din	= 'turtle_DBA_paper_din_Funda.mat';
	
	turtle_freq_name		= 'turtle_freq_Funda.mat';

   elseif turtle_nm == 0
	turtle_name		= 'Calib_test';
	name_table_agm	= 'Calib_test.csv'; 
	name_table_axy	= 'Calib_test.csv'; 
	name_table_calib = 'Calib_test.csv';
	turtle_raw_name			= 'Calib_test.mat';
	turtle_ypr_name			= 'Calib_test_ypr.mat';
	turtle_dive_name		= 'Calib_test_dive.mat';
	turtle_dive_plt_name	= 'Calib_test_dive_plt.mat';
	turtle_dive_fft_name	= 'Calib_test_dive_fft.mat';
	turtle_DBA_name			= 'Calib_test_DBA.mat';
	turtle_DBA_name_paper	= 'Calib_test_DBA_paper.mat';
	
	turtle_dive_name_din		= 'Calib_test_dive_din.mat';
	turtle_dive_plt_name_din	= 'Calib_test_dive_din_plt.mat';
	turtle_dive_fft_name_din	= 'Calib_test_dive_fft_din.mat';
	turtle_DBA_name_paper_din	= 'Calib_test_DBA_paper_din.mat';
	
	turtle_freq_name		= 'Calib_test_freq.mat';
end
