%% add path

added_once = 1;

addpath("fcn");
addpath("paper_dataset");
addpath("general_scripts");
addpath("dead_reck_trials");
addpath("main");
addpath("main_1_scripts");
addpath("main_2_scripts");
addpath("main_3_scripts");
addpath("main_4_scripts");
addpath("main_5_scripts");
addpath("save_scripts");
addpath("load_scripts");
addpath("csv_file");
addpath("csv_file\Turchia2023");
addpath("csv_file\Turchia2023\Banu-C");
addpath("csv_file\Turchia2023\Banu-C\axy");
addpath("csv_file\Turchia2023\Didar-F");
addpath("csv_file\Turchia2023\Emine-D");
addpath("csv_file\Turchia2023\Emine-D\axy");
addpath("csv_file\Turchia2023\Fati-E");
addpath("csv_file\Turchia2023\Fati-E\axy");
addpath("csv_file\Turchia2023\Melis-B");
addpath("csv_file\Turchia2023\Melis-B\axy");
addpath("csv_file\Turchia2023\Sevval-A");
addpath("csv_file\Turchia2023\Deniz");
addpath("csv_file\Turchia2023\Elif");
addpath("csv_file\Turchia2023\Funda");
addpath("csv_file\Turchia2024");
addpath("csv_file\Turchia2024\calibration\");

addpath("csv_file\Turchia2024\Enes");
addpath("csv_file\Turchia2024\Enes\axy");
addpath("csv_file\Turchia2024\Atakan");
addpath("csv_file\Turchia2024\Atakan\axy");
addpath("csv_file\Turchia2024\Fatma");
addpath("csv_file\Turchia2024\Fatma\axy");
addpath("csv_file\Turchia2024\Ilkim");
addpath("csv_file\Turchia2024\Ilkim\axy");
addpath("csv_file\Turchia2024\Nurdan");
addpath("csv_file\Turchia2024\Nurdan\axy");
addpath("csv_file\Turchia2024\Paula");
addpath("csv_file\Turchia2024\Paula\axy");
addpath("csv_file\Turchia2024\Arya");
addpath("csv_file\Turchia2024\Arya\axy");
addpath("csv_file\Turchia2024\Bihter");
addpath("csv_file\Turchia2024\Bihter\axy");
addpath("csv_file\Turchia2024\Erica");
addpath("csv_file\Turchia2024\Erica\axy");
addpath("csv_file\Turchia2024\Benedetta");
addpath("csv_file\Turchia2024\Benedetta\axy");